// <auto-generated>
//      This code was generated by HasFlagExtension.Generator.
//      changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using System;

namespace HasFlagExtension;

[AttributeUsage(AttributeTargets.Assembly | AttributeTargets.Enum)]
public class EnumNamingAttribute : Attribute {
    public NamingCase EnumNamingCase   { get; }
    public NamingCase MethodNamingCase { get; }
    
    public EnumNamingAttribute(NamingCase enumNamingCase, NamingCase methodNamingCase) {
        EnumNamingCase   = enumNamingCase;
        MethodNamingCase = methodNamingCase;
    }
}