// <auto-generated>
//      This code was generated by HasFlagExtension.Generator.
//      changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#pragma warning disable CS0436

using System;

namespace HasFlagExtension;

[AttributeUsage(AttributeTargets.Field)]
internal class ExcludeFlagAttribute : Attribute {
    public bool Exclude { get; }
    
    public ExcludeFlagAttribute(bool exclude = true) {
        Exclude = exclude;
    }
}