// <auto-generated>
//      This code was generated by HasFlagExtension.Generator.
//      changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using System;

namespace HasFlagExtension;

[AttributeUsage(AttributeTargets.Enum)]
public class ExcludeFlagEnumAttribute : Attribute {
    public bool Exclude { get; }
    
    public ExcludeFlagEnumAttribute(bool exclude = true) {
        Exclude = exclude;
    }
}