// <auto-generated>
//      This code was generated by HasFlagExtension.Generator.
//      changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using System;

namespace HasFlagExtension;

[AttributeUsage(AttributeTargets.Enum | AttributeTargets.Field, AllowMultiple = true)]
public class FlagGroupAttribute : Attribute {
    public string Group { get; }
    public string Prefix { get; }
    
    public FlagGroupAttribute(string group) {
        Group = group;
        Prefix = string.Empty;
    }
    
    public FlagGroupAttribute(string group, string prefix) {
        Group = group;
        Prefix = prefix;
    }
}