// <auto-generated>
//      This code was generated by HasFlagExtension.Generator.
//      changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#pragma warning disable CS0436

using System;

namespace HasFlagExtension;

[AttributeUsage(AttributeTargets.Enum | AttributeTargets.Field)]
internal class HasFlagPrefixAttribute : Attribute {
    public string Prefix { get; }
    
    public HasFlagPrefixAttribute(string prefix) {
        Prefix = prefix;
    }
}