<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <RootNamespace>HasFlagExtension.Sample</RootNamespace>
        <OutputType>exe</OutputType>
        <IsPackable>false</IsPackable>
        
        <LocalPackagingTest>false</LocalPackagingTest>
    </PropertyGroup>

    <ItemGroup Condition="'$(LocalPackagingTest)' == 'true'">
        <PackageReference Include="HasFlagExtension.Generator" Version="2026.1" OutputItemType="Analyzer" ReferenceOutputAssembly="false">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup Condition="'$(LocalPackagingTest)' == 'false'">
        <ProjectReference Include="../Src/Analyzers/HasFlagExtension.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
        <ProjectReference Include="../Src/CodeFixes/HasFlagExtension.CodeFixes.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
        <ProjectReference Include="../Src/Generator/HasFlagExtension.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>
</Project>
