// HasFlagExtension Generator
// Copyright (c) 2025 - 2026 KryKom

namespace HasFlagExtension.Generator;

internal static class Global {
    internal const string HFNS = nameof(HasFlagExtension);

    internal const string AUTOGEN_HEADER =
        """
        // <auto-generated>
        //    This code was generated by the HasFlagExtension.Generator (c) 2025 - 2026 KryKom.
        //    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
        // </auto-generated>
        """;

    internal const string VALUE_NAME = "val";

    internal static HashSet<T> ToHashSet<T>(this IEnumerable<T> enumerable) => [..enumerable];
    
    internal static Location GetAttributeLocation(AttributeData attr) => 
        attr.ApplicationSyntaxReference?.GetSyntax().GetLocation() ?? Location.None;
}