// HasFlagExtension Generator
// Copyright (c) 2026 KryKom

using System.Linq;
using HasFlagExtension.Generator;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;
using Xunit.Abstractions;

namespace HasFlagExtension.Tests;

public class AccessAndPrefixTests {
    
    private readonly ITestOutputHelper _testOutputHelper;
    public AccessAndPrefixTests(ITestOutputHelper testOutputHelper) {
        _testOutputHelper = testOutputHelper;
    }
    
    private const string ATTRIBUTE_SOURCE = 
        """
        using System;

        namespace HasFlagExtension;

        [AttributeUsage(AttributeTargets.Enum)]
        public class HasFlagPrefixAttribute : Attribute {
            
            public string Prefix { get; }
            
            public HasFlagPrefixAttribute(string prefix) {
                Prefix = prefix;
            }
        }
        """;

    private string GetTestEnumClass(string prefix, bool isIntern) => $$"""
        using System;
        using HasFlagExtension;

        namespace TestNamespace;

        [Flags]
        [HasFlagExtension.HasFlagPrefixAttribute("{{prefix}}")]
        {{(isIntern ? "internal" : "public")}} enum TestEnum {
            A,
            B,
            C
        }
        """;

    private string GetGeneratedClass(string prefix, bool isIntern) {
        var am = isIntern ? "internal" : "public";
        
        return
            $$"""
              // <auto-generated>
              //    This code was generated by the HasFlagExtension.Generator (c) 2026 KryKom.
              //    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
              // </auto-generated>

              using System.Diagnostics.Contracts;
              using System.Runtime.CompilerServices;
              using TestNamespace;

              namespace TestNamespace;

              {{am}} static partial class TestEnumExtensions {

                  /// <summary>
                  /// Returns true if the flag A is present in the value.
                  /// </summary>
                  [Pure]
                  [MethodImpl(MethodImplOptions.AggressiveInlining)]
                  {{am}} static bool Get{{prefix}}A(this TestNamespace.TestEnum val) => val.HasFlag(TestNamespace.TestEnum.A);

                  /// <summary>
                  /// Returns true if the flag B is present in the value.
                  /// </summary>
                  [Pure]
                  [MethodImpl(MethodImplOptions.AggressiveInlining)]
                  {{am}} static bool Get{{prefix}}B(this TestNamespace.TestEnum val) => val.HasFlag(TestNamespace.TestEnum.B);

                  /// <summary>
                  /// Returns true if the flag C is present in the value.
                  /// </summary>
                  [Pure]
                  [MethodImpl(MethodImplOptions.AggressiveInlining)]
                  {{am}} static bool Get{{prefix}}C(this TestNamespace.TestEnum val) => val.HasFlag(TestNamespace.TestEnum.C);

              #if NET10_0_OR_GREATER

                  extension(TestNamespace.TestEnum val) {

                      /// <summary>
                      /// Returns true if the flag A is present in the value.
                      /// </summary>
                      [Pure]
                      {{am}} bool {{prefix}}A => val.HasFlag(TestNamespace.TestEnum.A);

                      /// <summary>
                      /// Returns true if the flag B is present in the value.
                      /// </summary>
                      [Pure]
                      {{am}} bool {{prefix}}B => val.HasFlag(TestNamespace.TestEnum.B);

                      /// <summary>
                      /// Returns true if the flag C is present in the value.
                      /// </summary>
                      [Pure]
                      {{am}} bool {{prefix}}C => val.HasFlag(TestNamespace.TestEnum.C);
                  }
              #endif

              }
              """;
    }

    [Theory]
    [InlineData("Has", true)]
    [InlineData("Allow", true)]
    [InlineData("Log", true)]
    [InlineData("Has", false)]
    [InlineData("Allow", false)]
    [InlineData("Log", false)]
    public void GenerateHasFlagMethods(string prefix, bool isIntern) {
        var generator = new HasFlagExtensionGenerator();
        
        var driver = CSharpGeneratorDriver.Create(generator);
        
        var compilation = CSharpCompilation.Create(nameof(AccessAndPrefixTests),
            [
                CSharpSyntaxTree.ParseText(ATTRIBUTE_SOURCE),
                CSharpSyntaxTree.ParseText(GetTestEnumClass(prefix, isIntern)),
            ],
            [
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location)
            ]
        );
        
        var runResult           = driver.RunGenerators(compilation).GetRunResult();
        var generatedFileSyntax = runResult.GeneratedTrees.Single(t => t.FilePath.EndsWith("Extensions.g.cs"));

        _testOutputHelper.WriteLine(generatedFileSyntax.GetText().ToString());
        _testOutputHelper.WriteLine(GetTestEnumClass(prefix, isIntern));
        
        Assert.Equal(GetGeneratedClass(prefix, isIntern), generatedFileSyntax.GetText().ToString(), 
            ignoreLineEndingDifferences: true, ignoreWhiteSpaceDifferences: true, ignoreAllWhiteSpace: true);
    }
}