# HasFlagExtension
# by KryKom with love and care :)

name: Build HasFlagExtension

on:
  push:
    paths:
      - 'HasFlagExtension/**'
      - 'HasFlagExtension.Tests/**'

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest 

    env:
      Solution_Name: HasFlagExtension.sln
      Test_Project_Path: HasFlagExtension.Tests\HasFlagExtension.Tests.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
        
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Build Projects
      run: dotnet build

    - name: Execute unit tests
      run: dotnet test $env:Test_Project_Path --no-restore

    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
