# HasFlagExtension
# by KryKom with love and care :)

name: Publish HasFlagExtension to NuGet

on:   
  workflow_dispatch:

env:
  SolutionPath: ./HasFlagExtension.slnx
  ProjectPath: ./Src/Generator/HasFlagExtension.Generator.csproj
  TestProjectPath: ./Tests/HasFlagExtension.Tests.csproj
  SampleProjectPath: ./Samples/HasFlagExtension.Sample.csproj
  NugetOutputDir: ./nupkg/

jobs:
  build-test-publish:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore dependencies
      run: dotnet restore ${{ env.SolutionPath }}

    - name: Build solution
      run: dotnet build ${{ env.SolutionPath }} --configuration Release --no-restore
  
    - name: Execute unit tests
      run: dotnet test ${{ env.TestProjectPath }} --configuration Release --no-build

    - name: Run sample application
      run: dotnet run --project ${{ env.SampleProjectPath }} --configuration Release --no-build

    - name: Pack Generator
      run: dotnet pack ${{ env.ProjectPath }} --configuration Release --no-build --output ${{ env.NugetOutputDir }}

    - name: Push to NuGet
      run: |
        Get-ChildItem ${{ env.NugetOutputDir }}*.nupkg -Exclude *.symbols.nupkg | ForEach-Object {
          dotnet nuget push $_.FullName --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        }
      shell: pwsh
