# HasFlagExtension
# by KryKom with love and care :)

name: Test HasFlagExtension

on:
  push:
    paths:
      - 'HasFlagExtension/**'
      - 'HasFlagExtension.Tests/**'
      - '.github/workflows/test.yml'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest 

    env:
      SolutionName: ./HasFlagExtension.sln
      TestProjectPath: ./HasFlagExtension.Tests/HasFlagExtension.Tests.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Execute unit tests
      run: dotnet test ${{ env.TestProjectPath }}

    - name: Restore the application
      run: dotnet restore
